# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoHealth < Formula
  desc "A CLI/TUI tool that scans a project and shows an interactive health dashboard"
  homepage "https://github.com/FerrBen/repo-health"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FerrBen/repo-health/releases/download/v0.1.0/repo-health_0.1.0_darwin_amd64.tar.gz"
      sha256 "05cd3f73cce336848429599f57d516698118404c949ec2da261a525a4c4c19b2"

      def install
        bin.install "repo-health"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FerrBen/repo-health/releases/download/v0.1.0/repo-health_0.1.0_darwin_arm64.tar.gz"
      sha256 "3bc1bcbb2ebb6caab776992ced4d1f48d85eedde1efed8b8b74720e60e309433"

      def install
        bin.install "repo-health"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FerrBen/repo-health/releases/download/v0.1.0/repo-health_0.1.0_linux_amd64.tar.gz"
      sha256 "252ce360e032e24a0c972938b31cc5f20892f83fc266c512d574e4d23bea15fc"
      def install
        bin.install "repo-health"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FerrBen/repo-health/releases/download/v0.1.0/repo-health_0.1.0_linux_arm64.tar.gz"
      sha256 "254404d7c97adcb4160445e5c9aea51bdcebe9b8d4fd21d882d3037e71c32245"
      def install
        bin.install "repo-health"
      end
    end
  end

  test do
    system "#{bin}/repo-health", "--help"
  end
end
