# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoHealth < Formula
  desc "A CLI/TUI tool that scans a project and shows an interactive health dashboard"
  homepage "https://github.com/FerrBen/repo-health"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FerrBen/repo-health/releases/download/v0.1.1/repo-health_0.1.1_darwin_amd64.tar.gz"
      sha256 "135804024a37f18db45f2e51c29892c135de09b1244d9ac1d5eb1367e0eb990c"

      def install
        bin.install "repo-health"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FerrBen/repo-health/releases/download/v0.1.1/repo-health_0.1.1_darwin_arm64.tar.gz"
      sha256 "ec6054fa30c9525ba5d021da454519ce6c0fe8943ac024111d10d87ca92d77c2"

      def install
        bin.install "repo-health"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FerrBen/repo-health/releases/download/v0.1.1/repo-health_0.1.1_linux_amd64.tar.gz"
      sha256 "38b3b52c46429d52a4a9b46bec66509bcaba04fb98e1ca4659453fbf656aaee5"
      def install
        bin.install "repo-health"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FerrBen/repo-health/releases/download/v0.1.1/repo-health_0.1.1_linux_arm64.tar.gz"
      sha256 "83fb8461f01939c1d13e14287975c554d973f13c81bc6d4f3d27a9c7cb1452be"
      def install
        bin.install "repo-health"
      end
    end
  end

  test do
    system "#{bin}/repo-health", "--help"
  end
end
